version: "3" 
services: 
  wordpress: 
    image: wordpress:5.7-php7.4 
    restart: unless-stopped 
    ports: 
      - 9000:80
    environment: 
      WORDPRESS_DB_HOST: mysql:3306 
      WORDPRESS_DB_USER: training_wordpress 
      WORDPRESS_DB_PASSWORD: wordpress 
    volumes:
      - .:/var/www/html 

  mysql: 
    image: mysql:5.7 
    restart: unless-stopped 
    environment: 
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: wordpress 
      MYSQL_RANDOM_ROOT_PASSWORD: wordpress
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./mysql:/var/lib/mysql

  webserver:
    image: nginx:alpine
    container_name: nginx_laravel
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
